### ISSUE TITLE
Unable to deploy new project

### ISSUE THREAD

**Issue by tylers-username** [platformsh/platformsh-example-magento1#3]
Will GITs version history get in the way of a deployment? I cloned my original Magento repo and moved contents to /web. I then cloned platformsh/platformsh-example-magento1 and copied the contents into the root directory so that the file structure of my Magento get repo matches what is shown here. I pushed to the server and am seeing this error

    Validating submodules.
    Validating configuration files.
    E: Error parsing configuration files:
        - services: Error loading file: No `.platform/services.yaml` file found in the repository.
        - routes: Error loading file: No `.platform/routes.yaml` file found in the repository.
        - applications: No `.platform.app.yaml` file found anywhere in the repository.

**Comment by JGrubb** [comment]
Hey Tyler,

It looks like your copy operation did not move the .platform directory and the .platform.app.yaml files into your project.  That’s why it’s failing.

**Comment by JGrubb** [comment]
The "validating submodules" line also makes me nervous.  The `.git` directory from this project (not yours) should be deleted, not moved into your project.

**Comment by tylers-username** [comment]
@JGrubb - thanks for the prompt response. Before posting here, I'd remove .gitmodules - I didn't need it anyway. This is really a platform.sh technical question and not an issue with the instructions provided here, however I'd love to get some feedback.

 I was hoping to preserve my GIT history which is why I cloned my repo and then modified it to match this repo. However, I was only able to successfully push after removing the `.git` directory. This is just a test to see how I feel about platform.sh, so if there is anyway to preserve my repo history, I'd love to hear feedback.

**Comment by OriPekelman** [comment]
You do not need to remove the history, simply, you did not copy over the configuration files.

In many operating systems (like OS X and Linux) these files will be hidden in the "Finder" or file browser by default. 

In order for this to work you need to copy the files `.platform.app.yaml` and the directory `.platform` which is what the platform.sh error message is telling you.

**Comment by tylers-username** [comment]
These files were part of the  commit I was pushing that resulted in these errors.
